### PR TITLE
Expand external oasis repo removal instructions

### PR DESCRIPTION
**Pull request by DrDaveD**
This adds more complete instructions for handling removal of an OSG cvmfs repository.

Related to osg-htc/docs#20.

### CODE REVIEW

**Comment by DrDaveD** [comment]
Github doesn't give me an option to request a reviewer, so @jthiltges please review.

@brianhlin @CannonLock the CI check failure is not obviously related to the changes in this PR.

**Comment by CannonLock** [comment]
Can confirm that the errors are not related to this page update.

**Review by jthiltges — APPROVED** [review]
Changes LGTM.

For the appropriate contacts, could we refer to OSG topology resources instead of (or in addition to) specific people?

I'm finding BNL_ATLAS_CVMFS_Squid and USCMS-FNAL-WC1-SQUID, but not sure if those are the right ones, or if they still need to be added.

**Comment by DrDaveD** [comment]
Using topology sounds like a good idea to me.  Those SQUID resources aren't exactly the same as the stratum 1s, which are not registered, but they will be administered by the same people.  Merina would need to be added to the FNAL entry.

That could be done in a separate PR after Merina is added.  Do you have permission to merge this PR?

**Comment by jthiltges** [comment]
Apparently yes! Thanks Dave!

**Pull request merged**
